### ISSUE TITLE
从Oracle数据库导入元数据时会报ava.lang.AbstractMethodError: oracle.jdbc.driver.T4CConnection.setClientInfo(Ljava/util/Properties;)V错误

### ISSUE THREAD

**Issue by Arcko** [ma459006574/kettle-manager#6]
2017-11-04 08:07:31 ERROR [qtp1161667116-55 - ActionHandler.java:128] /meta/doImports
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.jfinal.aop.Invocation.invoke(Invocation.java:87)
        at com.jfinal.plugin.activerecord.tx.Tx.intercept(Tx.java:77)
        at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
        at com.eova.interceptor.LoginInterceptor.intercept(LoginInterceptor.java:109)
        at com.jfinal.aop.Invocation.invoke(Invocation.java:67)
        at com.jfinal.core.ActionHandler.handle(ActionHandler.java:74)
        at com.jfinal.plugin.druid.DruidStatViewHandler.handle(DruidStatViewHandler.java:75)
        at com.jfinal.core.JFinalFilter.doFilter(JFinalFilter.java:72)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:365)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:937)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:998)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.jfinal.aop.Invocation.invoke(Invocation.java:73)
        ... 30 more
Caused by: java.lang.AbstractMethodError: oracle.jdbc.driver.T4CConnection.setClientInfo(Ljava/util/Properties;)V
        at com.alibaba.druid.filter.FilterChainImpl.connection_setClientInfo(FilterChainImpl.java:574)
        at com.alibaba.druid.filter.FilterAdapter.connection_setClientInfo(FilterAdapter.java:996)
        at com.alibaba.druid.filter.FilterChainImpl.connection_setClientInfo(FilterChainImpl.java:570)
        at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.setClientInfo(ConnectionProxyImpl.java:444)
        at com.alibaba.druid.pool.DruidPooledConnection.setClientInfo(DruidPooledConnection.java:1029)
        at com.eova.common.utils.db.DsUtil.getDatabaseMetaData(DsUtil.java:48)
        at com.eova.common.utils.db.DsUtil.getColumnInfoByConfigName(DsUtil.java:182)
        at com.eova.common.utils.db.DsUtil.getColumnInfoByConfigName(DsUtil.java:162)
        at com.eova.core.meta.MetaController.doImports(MetaController.java:212)
        ... 35 more

**Comment by Arcko** [comment]
![issue02](https://user-images.githubusercontent.com/17232/32400820-1ade92e8-c140-11e7-8f95-e549313ff6d7.png)

**Comment by majinju** [comment]
这个是eova的功能，我也只是在eova的基础上来实现kettle的管理功能，可以去eova的论坛去问问
